### ISSUE TITLE
在代码中看到PATH是加载的traj.yaml中的路径，该文件中描述轨迹的参数都代表什么含义？

### ISSUE THREAD

**Issue by IngaVS** [ZJU-FAST-Lab/CMPCC#1]
```
        num_segment  = node["num_segment" ].as<int> ();
        traj_order = 5;
        K_data = node["K"].as <std::vector<double>>();
        K_max = node["K_max"].as <int>();？
        range  = node["range" ].as < std::vector < double >> ();
        long secs = node["final_time"]["secs"].as<long>() - node["start_time"]["secs"].as<long>();
        long nsecs = node["final_time"]["nsecs"].as<long>() - node["start_time"]["nsecs"].as<long>();
        global_traj_time = secs + nsecs*1e-9;
        thetaMax = global_traj_time;
        vector<double> coef_x = node["coef_x"].  as < vector < double >> ();//x轴轨迹参数 
        vector<double> coef_y = node["coef_y"].  as < vector < double >> ();//y轴轨迹参数
        vector<double> coef_z = node["coef_z"].  as < vector < double >> ();//z轴轨迹参数
        vector<double> tt     = node["time"].    as < vector < double >> ();//时间
        vector<double> ta     = node["time_acc"].as < vector < double >> ();//?
        vector<double> a      = node["a"].       as < vector < double >> ();//？
        vector<double> b      = node["b"].       as < vector < double >> ();//？
        vector<double> s      = node["s"].       as < vector < double >> ();//?
```
完整描述一条贝塞尔轨迹，只需要参数和时间就可以了吧？
想问一下traj.yaml中的K_data，ta,a,b,s都是什么含义呢？

**Comment by GaaiLam** [comment]
你好，traj.yaml中的参数是teach-repeat-replan的工作中全局轨迹优化时生成的轨迹参数，这些参数是时空优化后的中间变量，比较复杂，获得轨迹信息的方法已经封装在Map::getGlobalCommand函数里了，如果你想搞清楚每一个参数的意义，需要了解一下trr的工作：https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan。实际上对于cmpcc来说前端的全局轨迹可以不必是贝塞尔，普通的多项式曲线也可以，甚至只拿path planning的结果做前端也是可以work的。

**Comment by IngaVS** [comment]
> 你好，traj.yaml中的参数是teach-repeat-replan的工作中全局轨迹优化时生成的轨迹参数，这些参数是时空优化后的中间变量，比较复杂，获得轨迹信息的方法已经封装在Map::getGlobalCommand函数里了，如果你想搞清楚每一个参数的意义，需要了解一下trr的工作：[https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan。](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan%E3%80%82)
> 实际上对于cmpcc来说前端的全局轨迹可以不必是贝塞尔，普通的多项式曲线也可以，甚至只拿path planning的结果做前端也是可以work的。

**Comment by IngaVS** [comment]
> 你好，traj.yaml中的参数是teach-repeat-replan的工作中全局轨迹优化时生成的轨迹参数，这些参数是时空优化后的中间变量，比较复杂，获得轨迹信息的方法已经封装在Map::getGlobalCommand函数里了，如果你想搞清楚每一个参数的意义，需要了解一下trr的工作：[https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan。](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan%E3%80%82)
> 实际上对于cmpcc来说前端的全局轨迹可以不必是贝塞尔，普通的多项式曲线也可以，甚至只拿path planning的结果做前端也是可以work的。

**Comment by IngaVS** [comment]
![image](https://user-images.githubusercontent.com/18420049/89998113-b0b90080-dcbf-11ea-991b-0ac4c5146ef0.png)
对于x的最后三个参数不是很理解

**Comment by GaaiLam** [comment]
\theta 是一个状态变量，是个标量，他的物理意义是全局轨迹上的时间。而后面两项分别是他关于时间的一阶和二阶导数。如果v_theta始终等于1，那么就是飞机始终沿着全局轨迹在飞行，如果v_theta小于1，那就是飞得比全局轨迹慢，因而在目标函数中加了一项-v_\theta便可以优化progress。

**Comment by IngaVS** [comment]
谢谢！！
