### ISSUE TITLE
ubuntu16.04 with ROS KINETIC   tf issues maybe?

### ISSUE THREAD

**Issue by Joeyyuenjoyslife** [ZJU-FAST-Lab/CMPCC#2]
HI Jialin,  I'm trying to use cmpcc to perform a comparison experiment on my ubuntu16.04 with ROS KINETIC. After I run the simulation.sh , I got some errors like this:

[ERROR] [1619329490.998581958]: Ignoring transform for child_frame_id "body" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (0.000000 0.000000 0.000000 1.000000)

It seems the tf didin't work well .  and I checked some rostopic , found that most msg seems did not be published.  But all the rosnode launched successfully.

I have try to exam the code, but didn't figure out.  Have you ever try to run this simulation on ubuntu16.04? or could you give me some hint about where should I pay attention to modify the code ?

**Comment by GaaiLam** [comment]
Thanks for reporting bugs! The reason is that the Eigen method "normalized()" would not judge if the denominator is zero in low version (ros kinetic). I have fixed the bug in the last commit [20b367c](https://github.com/ZJU-FAST-Lab/CMPCC/commit/20b367c2e633beb17bd2f91ea88e0f6f02c6416f)

**Comment by GaaiLam** [comment]
> HI Jialin, I'm trying to use cmpcc to perform a comparison experiment on my ubuntu16.04 with ROS KINETIC. After I run the simulation.sh , I got some errors like this:
> 
> [ERROR] [1619329490.998581958]: Ignoring transform for child_frame_id "body" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (0.000000 0.000000 0.000000 1.000000)
> 
> It seems the tf didin't work well . and I checked some rostopic , found that most msg seems did not be published. But all the rosnode launched successfully.
> 
> I have try to exam the code, but didn't figure out. Have you ever try to run this simulation on ubuntu16.04? or could you give me some hint about where should I pay attention to modify the code ?

Thanks for reporting bugs! The reason is that the Eigen method "normalized()" would not judge if the denominator is zero in low versions (ros kinetic). I have fixed the bug in the last commit [20b367c](https://github.com/ZJU-FAST-Lab/CMPCC/commit/20b367c2e633beb17bd2f91ea88e0f6f02c6416f).

**Comment by Joeyyuenjoyslife** [comment]
The last commit works well in Ubuntu 16.04 . Thanks for your help!
