### ISSUE TITLE
Points and Normals in corridor.yaml

### ISSUE THREAD

**Issue by GChasing** [ZJU-FAST-Lab/CMPCC#5]
The safe flight corridor(SFC) is generated via corridor.yaml, which is represented by convex hull. This is what i only know. 

But, when i see the files "corridor.yaml" , 
I'm curious about the meaning of "points and normals" in the corridor.yaml. 
And how i generate the SFC manually?

Best wishes, and hope for your reply

**Comment by GaaiLam** [comment]
> 

The corridor used in this work is generated from our previous work [TRR](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan). The file 'corridor.yaml' is just a copy of ros message of the generated corridor. If you are interested in methods of generating flight corridor, you can also refer to some other repos: [IRIS](https://github.com/rdeits/iris), [Galaxy](https://github.com/StarryN/Galaxy), [DecompROS](https://github.com/sikang/DecompROS)
