### ISSUE TITLE
Resource not found: trr_global_planner

### ISSUE THREAD

**Issue by YUJX19** [ZJU-FAST-Lab/CMPCC#6]
How can I control the flight of a drone and add wind disturbance?
 When I try to `roslaunch cmpcc flyfly.launch`, it reports a '**Resource not found: trr_global_planner**' error. Does anyone know how to solve this issue? Thank you very much~

**Comment by GaaiLam** [comment]
> How can I control the flight of a drone and add wind disturbance? When I try to `roslaunch cmpcc flyfly.launch`, it reports a '**Resource not found: trr_global_planner**' error. Does anyone know how to solve this issue? Thank you very much~

https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan
