### ISSUE TITLE
About reference trajectory

### ISSUE THREAD

**Issue by ChanJoon** [ZJU-FAST-Lab/CMPCC#7]
Hi. I'm undergrad student.
I'm now trying to re-implement your code with other qp solver.

But I have trouble with handling reference trajectory...
how could you generate traj.yaml with [Teach-Repeat-Replan](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan)?

Can you give me some detailed explanation about each parameters?
I want to get those parameters online(with ros msg nav_msgs::Path).

Thanks for works and sharing your code.

**Comment by GaaiLam** [comment]
> Hi. I'm undergrad student. I'm now trying to re-implement your code with other qp solver.
> 
> But I have trouble with handling reference trajectory... how could you generate traj.yaml with [Teach-Repeat-Replan](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan)?
> 
> Can you give me some detailed explanation about each parameters? I want to get those parameters online(with ros msg nav_msgs::Path).
> 
> Thanks for works and sharing your code.

just write the msg to file like:  rostopic echo _Topic Name_ >> traj.yaml
u can change any other reference trajectory if u like

**Comment by ChanJoon** [comment]
Thank you for your reply!
I have another question. In my solver, $v_{\theta}$ is not close to 1. In your paper, $v_{\theta}$ represents the speed of the drone relative to the global reference trajectory.
However, while optimizing the objective function, how can $v_{\theta}$  converge to 1? Shouldn't it just keep increasing?
